# -*- coding: utf-8 -*-
"""Chest X-Ray Pneumonia Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKmjugdVYUnMrb3WhQgBrARXHGO50Lez
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,BatchNormalization, Dropout,GlobalAveragePooling2D,BatchNormalization
from keras.models import Sequential,Model
from keras.utils import image_dataset_from_directory
from keras.optimizers import Adam

import os
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_44a35dd2fa66794bd3ae4393f5f78f93'

!pip install -q kaggle
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia
!unzip -q chest-xray-pneumonia.zip -d /content/xray_data

train_data=image_dataset_from_directory(
    directory='/content/xray_data/chest_xray/train',
    labels='inferred',
    batch_size=32,
    validation_split=0.15,
    image_size=(128,128),
    color_mode='grayscale',
    subset='training',
    seed=42
)
validation_data=image_dataset_from_directory(
    directory='/content/xray_data/chest_xray/val',
    labels='inferred',
    batch_size=32,
    validation_split=0.15,
    image_size=(128,128),
    subset='validation',
    color_mode='grayscale',
    seed=42
)
test_data=image_dataset_from_directory(
    directory='/content/xray_data/chest_xray/test',
    labels='inferred',
    batch_size=32,
    image_size=(128,128),
    color_mode='grayscale'
)

def process(image,label):
  image=tf.cast(image/255.,tf.float32)
  return image,label
train_data=train_data.map(process)
validation_data=validation_data.map(process)
test_data=test_data.map(process)

model=Sequential()

model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,1)))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))


model.add(Conv2D(64,(3,3),activation='relu'))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))


model.add(Conv2D(128,(3,3),activation='relu'))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))


model.add(Conv2D(256,(3,3),activation='relu'))
model.add(Conv2D(256,(3,3),activation='relu'))
model.add(Conv2D(256,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))

model.add(Flatten())

model.add(Dense(256,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(train_data,epochs=15,validation_data=validation_data)

test_loss, test_accuracy = model.evaluate(test_data)
print(f"Test Accuracy: {test_accuracy:.4f}")

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

y_true = []
y_pred = []

for images, labels in test_data:
    preds = model.predict(images, verbose=0)
    preds = (preds > 0.5).astype(int).flatten()
    y_true.extend(labels.numpy())
    y_pred.extend(preds)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred, target_names=['NORMAL', 'PNEUMONIA']))

model.save('pneumonia_model.h5')

from google.colab import files
files.download('pneumonia_model.h5')

# from tensorflow.keras.applications import VGG16

# model_vgg=VGG16(weights='imagenet',include_top=False,input_shape=(128,128,3))

# model_vgg.trainable=False

# y=model_vgg.output
# y=GlobalAveragePooling2D()(y)
# y=Dense(256,activation='relu')(y)
# # y=Dropout(0.5)(y)
# Output=Dense(1,activation='sigmoid')(y)

# model_final=Model(inputs=model_vgg.input,outputs=Output)

# model_final.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.0001),metrics=['accuracy'])

# from keras.callbacks import EarlyStopping
# callback=EarlyStopping(
#     monitor='val_loss',
#     patience=7,
#     restore_best_weights=True
# )

# model_final.fit(train_data,epochs=10,validation_data=validation_data,callbacks=callback)

# test_loss, test_accuracy = model_final.evaluate(test_data)
# print(f"Test Accuracy: {test_accuracy:.4f}")

# 20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 140ms/step - accuracy: 0.8301 - loss: 0.6530
# Test Accuracy: 0.8301

